### ISSUE TITLE
Embotic Title covers tabs | Samsung Galaxy S9+

### ISSUE THREAD

**Issue by SuperEvilLuke** [xdlivecat/EmboticApp#6] opened 2024-03-01 19:58 UTC
![image](https://github.com/xdlivecat/EmboticApp/assets/97245327/110f2fee-16cc-4e7f-bb5a-cd8b3127a99e)
As you can see in the image provided, the name tab thing is covering the icons to navigate to different tabs

**Comment by xdlivecat** [comment] 2024-03-01 20:05
classic issue of me not properly making the layout, will fix

**Comment by SuperEvilLuke** [comment] 2024-03-01 20:07
you also cannot access them in portrait

**Comment by xdlivecat** [comment] 2024-03-01 20:19
seem to have broken it even more

**Comment by xdlivecat** [comment] 2024-03-01 20:38
@SuperEvilLuke Not an issue with action bar, seems to be an issue with the actual site as even after removing it the tabs are still nowhere

**Comment by TheAutisticChicken** [comment] 2024-03-01 20:43
yeah something broke there

**Comment by xdlivecat** [comment] 2024-03-02 10:53
Issue not fixable on my end, closing

**Comment by xdlivecat** [comment] 2024-03-07 18:24
After more testing I can confirm it is an issue on my end and that the WebView is being cut off at the top. Will fix this in V1.32

**Comment by xdlivecat** [comment] 2024-03-10 12:31
Issue fixed in v1.31 (I can't keep track of updates is it 1.32 or)

**Comment by SuperEvilLuke** [comment] 2024-03-11 02:18
ok

**Comment by xdlivecat** [comment] 2024-04-15 17:02
kind of fixed itself tbf, tabs are now hidden in a menu at the bottom following a ui change

**Closed by xdlivecat** 2024-04-15 17:02 UTC
